### ISSUE TITLE
Search by id?

### ISSUE THREAD

**Issue by omerinero** [jdrouet/tmdb-api#24]
Hi there,
Seems we can't search by id or its just me not being able to find it?

Thanks

**Comment by jdrouet** [comment]
Hey!
You can't "search" by `id` but you [can get the details of a TVShow by its `id`](https://docs.rs/tmdb-api/latest/tmdb_api/tvshow/details/struct.TVShowDetails.html) or [the details of a movie by its `id`](https://docs.rs/tmdb-api/latest/tmdb_api/movie/details/struct.MovieDetails.html).
If you think about a particular api endpoint on tmdb, feel free to open a PR 😉
