### ISSUE TITLE
Implement `std::error::Error` for error types?

### ISSUE THREAD

**Issue by George-Miao** [jdrouet/tmdb-api#61]
Currently except `ClientBuilderError`, none of the errors are std compatible, which makes it very hard to work with crates like anyhow and eyre. It would be nice to have them implemented. I'll willing to make a PR if needed.

**Comment by HakanVardarr** [comment]
Why you are not using thiserror crate for errors? They can come in handy in some situations.

**Comment by George-Miao** [comment]
I'm writing a bin crate and won't be benefit from thiserror.

**Comment by jdrouet** [comment]
Fixed!
