### ISSUE TITLE
make client abstract

### ISSUE THREAD

**Issue by jdrouet** [jdrouet/tmdb-api#67]
In order to give the user the ability to have a feature reach client (like implementing a rate limiting system), we should allow them to implement their own.
To do that, we should have a client trait that anybody could implement.

**Comment by agmbk** [comment]
How would one simply add a before/after request ? Without copying all the current implementation.

**Comment by jdrouet** [comment]
You just need to implement `crate::client::Executor` on a struct that would wrap the current default one.

Something like (I didn't test it)
```rust
struct MyExecutor {
  inner: tmdb_api::client::reqwest::ReqwestExecutor,
}


#[async_trait::async_trait]
impl super::prelude::Executor for MyExecutor {
    async fn execute<T: serde::de::DeserializeOwned>(
        &self,
        url: &str,
        params: Vec<(&str, Cow<'_, str>)>,
    ) -> Result<T, crate::error::Error> {
        // before
        let result = self.inner.execute(url, params).await;
        // after
        result
    }
}
```
